-- MySQL Script generated by MySQL Workbench
-- dom 17 nov 2019 10:50:01 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FinanceLibre
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `FinanceLibre` ;

-- -----------------------------------------------------
-- Schema FinanceLibre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FinanceLibre` ;
USE `FinanceLibre` ;

-- -----------------------------------------------------
-- Table `FinanceLibre`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinanceLibre`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinanceLibre`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinanceLibre`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `currency` VARCHAR(45) NULL,
  `balance` DOUBLE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_account_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `FinanceLibre`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinanceLibre`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinanceLibre`.`transaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` DOUBLE NOT NULL,
  `short` VARCHAR(45) NOT NULL,
  `description` VARCHAR(300) NULL,
  `date` DATETIME(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinanceLibre`.`account_has_transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinanceLibre`.`account_has_transaction` (
  `account_id` INT NOT NULL,
  `transaction_id` INT NOT NULL,
  PRIMARY KEY (`account_id`, `transaction_id`),
  INDEX `fk_account_has_transaction_transaction1_idx` (`transaction_id` ASC) VISIBLE,
  INDEX `fk_account_has_transaction_account1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_has_transaction_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `FinanceLibre`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_has_transaction_transaction1`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `FinanceLibre`.`transaction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
